### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fnenuwnar**
[Review on Reviewable](https://reviewable-dev-fnenu.firebaseapp.com/reviews/fnenwnar/stuff/1)

### CODE REVIEW

**Comment by fnenuwnar** [comment]
:sparkle: :sparkler: :sparkles: :sparkling_heart: :horse: (why is there no unicorn?) chrome on mac

---

---

<sup>**[README.md, line 1 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjD3ll-CgjwbeY0HT)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L1)):</sup>
:lantern: :ice_cream: :icecream:  :smiling_imp: chrome on mac

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenu** [comment]
---

<sup>**[README.md, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjv3zJFuOcoUc00FW)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L4)):</sup>
Did you even check this? Seriously! x is a number and now you're setting it to a string. What _is_ the world coming to? :unamused:  :banana: :panda_face: 

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenuwnar** [comment]
---

<sup>**[README.md, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjv3zJFuOcoUc00FW)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L4)):</sup>
:hatching_chick: :rage: :rage1: :rage2: :rage3: :rage4:

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenu** [comment]
---

<sup>**[README.md, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjv3zJFuOcoUc00FW)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L4)):</sup>
:cool: :arrow_down: :rage: :hurtrealbad: 

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenu** [comment]
:8ball: 

---

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenu** [comment]
Let's :see_no_evil: or :seedling: ?

---

<sup>**[README.md, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjv3zJFuOcoUc00FW)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L4)):</sup>
@fnenu talk to myself

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenu** [comment]
<sup>**[README.md, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjv3zJFuOcoUc00FW)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L4)):</sup>
@fnenuwnar hello there

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenu** [comment]
<sup>**[README.md, line 1 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/1#-JmXjD3ll-CgjwbeY0HT)** ([raw file](https://github.com/fnenwnar/stuff/blob/a553240464a66eda9ae55e2328074b8b60fd6aea/README.md#L1)):</sup>
:rabbit: :panda_face: :koala: :bear: :penguin: :cat: :dog: :elephant: :rat: :mouse: :pig: :cow: :fish: :bird: @fnenu @fnenwnar/owners 

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenuwnar** [comment]
@fnenu hello

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/1)

**Comment by fnenuwnar** [comment]
@fnenu hello

**Pull request merged**
