### PR TITLE
Something

### PR DESCRIPTION
**Pull request by fnenu**
dum di dum

[Review on Reviewable](https://reviewable-dev-fnenu.firebaseapp.com/reviews/fnenwnar/stuff/5)

### CODE REVIEW

**Comment by fnenu** [comment]
+enhancement 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+question 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-custard

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+bug

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+(help wanted) 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+duplicate 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+invalid 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+wontfix 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-invalid

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
lalalala -(help wanted)

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
:+bug:

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-bug

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
:+bug:

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+backend

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-question 
+bug

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+invalid 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
The rain in spain -bug

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+question 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+bug 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
something or other

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-invalid 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+invalid +question +blah

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+wontfix 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-wontfix 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+:+1:

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+:+1: 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
:heart:

---

<sup>**[something.html, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/5#-JnbxrnEOaAhUDTyRI6c)** ([raw file](https://github.com/fnenwnar/stuff/blob/632316f87d20c18a8cf8b6c2bca7c42b4a4b3413/something.html#L4)):</sup>
:heart: :sparking_heart:

---

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
:heart: :sparkling_heart: +duplicate +enhancement -invalid 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+@fnenuwnar 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
Now I'm going to pass over to myself +@fnenu

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+bug +@fnenu @fnenuwnar :+1: :headphones:

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenuwnar** [comment]
:sparkles: :hearts:

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenuwnar** [comment]
+@fnenu 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenuwnar** [comment]
+@fnenuwnar 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-(@fnenu) 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
+:+1: 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-(help wanted) 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-:+1: -(@fnenu) -bug -duplicate -enhancement 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Comment by fnenu** [comment]
-invalid -question -wontfix 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/5)

**Pull request closed without merging**
