### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by fnenuwnar**
Reverts fnenwnar/stuff#3

[Review on Reviewable](https://reviewable.io/reviews/fnenwnar/stuff/4)

### CODE REVIEW

**Comment by fnenu** [comment]
+(help wanted) 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/4)

**Comment by fnenu** [comment]
+bug 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/4)

**Comment by fnenu** [comment]
-(help wanted)

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/4)

**Comment by fnenu** [comment]
+duplicate 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/4)

**Comment by fnenuwnar** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[README.md, line 4 [r1]](https://localhost:8080/reviews/fnenwnar/stuff/4#-JqwI0wUC3vk6e0zPKYx)** ([raw file](https://github.com/fnenwnar/stuff/blob/dd43812560a2ba9fd58d6f14723d24c990f70781/README.md#L4)):</sup>
so bad, very very bad! number != string

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/4)

**Comment by fnenu** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- README.md @ r1

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenwnar/stuff/4)

**Pull request merged**
